### ISSUE TITLE
Definition of "Role"

### ISSUE THREAD

**Issue by joshmue** [SovereignCloudStack/Design-Docs#1]
> A role is a group of Identities connected with a set of Access Rights for Modules of SCS.

Being used to e. g. Kubernetes wording, this may be confusing. E. g. in Kubernetes, a role defines some set of permissions. This role can then be bound to an user, a group or similar.

CC @stunivention

**Comment by garloff** [comment]
I agree with Joshua here -- I have also seen the term "role" used in the sense of "a set of permissions". Usually one that groups certain things like "has read-only access to some set X of services" => "X observer" or the roles Read, Triage, Write, Maintain, Admin that exist in github.
Users or groups then typically get access rights by assigning one or several roles to them.

**Comment by stunivention** [comment]
You are right, roles and groups are two different things, they should not be mixed in the definition. I updated the "Role" definition.
