### ISSUE TITLE
SCS spec draft 0.1 contains discontinued OpenStack services

### ISSUE THREAD

**Issue by ttx** [SovereignCloudStack/Design-Docs#15]
SCS-Spec.md mentions Karbor as an optional service.
Karbor was removed in the upcoming Wallaby release, it should probably not be mentioned (even as optional) in the spec.
Freezer offers backup-as-service and may be used as an alternative, depending on the use case.

**Comment by garloff** [comment]
Thanks Thierry! 
Feel free to submit a PR or to just add a +1 to PR #16. 
--Kurt

**Comment by garloff** [comment]
Fixed with PR #16. Thanks, Thierry!
