### ISSUE TITLE
Document release versioning scheme

### ISSUE THREAD

**Issue by berendt** [SovereignCloudStack/Design-Docs#28]

**Comment by frosty-geek** [comment]
Releases should follow a similar structure like https://github.com/kinvolk/manifest/releases

**Comment by frosty-geek** [comment]
The relationship to the sub-project version management must be specified, e.g. https://releases.openstack.org/wallaby/index.html, but it should always be "machine parsable".

**Comment by fkr** [comment]
Since #29 was merged - can this be closed? @frosty-geek @berendt ?
