### ISSUE TITLE
Naming scheme of SCS Roles

### ISSUE THREAD

**Issue by tinguin** [SovereignCloudStack/Design-Docs#3]
We should rethink the naming scheme for the SCS Roles. Especially when it comes to the Kubernetes-* roles names like Operator and Deployment can lead to confusion as these are named entities in the Kubernetes world.

Maybe terms like Instance instead of Deloyment and Admin instead of Operator could fit, too, and avoid the possible confusion.

**Comment by stunivention** [comment]
As of now we are free to do so, the names were a "best guess". @tinguin  - can you propose changes in a pull request?

Feel free to add more roles based on the needs you've seen in your deployments.

**Comment by fkr** [comment]
I'd suggest to close this issue.  @garloff?

**Comment by fkr** [comment]
Will close now.
