### ISSUE TITLE
Competition with dfinity

### ISSUE THREAD

**Issue by tkvogt** [SovereignCloudStack/Design-Docs#4]
When you start a new project, you should be fully aware of the competition, try to be as innovative and modern as possible.

How innovative do you think you are compared to https://dfinity.org ?

What if in ten years there will be much less data centers?
An 8 core, 32GB AWS instance costs between 167$ to 270$ per month (t2.x2large).
My private machine costs ~14$ energy costs per month and has similar computing power. And its idling most of the time.
I would rather bet on dfinity or similar projects than on data centers.

**Comment by garloff** [comment]
Sorry, I'm not interested in this discussion.
